export const userConstants = {
	REQUEST: 'REQUEST',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	REGISTER: 'REGISTER',
	LIST_USERS: 'LIST_USERS',
	DELETE: 'DELETE',
	RESET_ERROR: 'RESET_ERROR',
	ERROR: 'ERROR'
}